#!/usr/bin/env python3
"""Weekly trend digest — diff RADAR.md snapshots over the last 7 days.

Reads git history for RADAR.md, extracts per-snapshot (category, repo, number)
tuples via regex, and emits WEEKLY.md summarizing what appeared, persisted,
and vanished. Run once a week via the weekly workflow.

Zero deps beyond git + stdlib. RADAR.md's shape is generated by radar.py so
we control the format we parse — no markdown parser needed.
"""

from __future__ import annotations

import re
import subprocess
import sys
from collections import defaultdict
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).parent
WEEKLY_PATH = REPO_ROOT / "WEEKLY.md"
RADAR_FILENAME = "RADAR.md"

WINDOW_DAYS = 7

CATEGORY_HEADING = re.compile(r"^## (.+?)$")
ISSUE_LINE = re.compile(
    r"^-\s+\[(?P<kind>[^\]]+)\]\s+"                # [Bug]
    r"(?:[^\[]*?)"                                  # optional flags between kind and link
    r"\[#(?P<num>\d+)\]\(https://github\.com/(?P<repo>[^/]+/[^/]+)/issues/\d+\)"
    r"\s+(?P<title>.+?)$"
)
# Section titles we skip when tracking categories.
NON_CATEGORY_SECTIONS = {"Contents"}


@dataclass(frozen=True)
class IssueRef:
    category: str
    repo: str
    number: int
    kind: str
    title: str

    @property
    def key(self) -> tuple[str, int]:
        return (self.repo, self.number)


def run(cmd: list[str]) -> str:
    return subprocess.run(cmd, capture_output=True, text=True, check=True).stdout


def list_snapshots(window_days: int) -> list[tuple[str, datetime]]:
    """Return [(sha, committed_at)] for RADAR.md commits in the window, oldest first."""
    since = (datetime.now(timezone.utc) - timedelta(days=window_days)).isoformat()
    out = run(["git", "log", f"--since={since}", "--format=%H|%aI", "--", RADAR_FILENAME])
    lines = [ln for ln in out.strip().split("\n") if ln]
    snaps = []
    for ln in lines:
        sha, iso = ln.split("|", 1)
        snaps.append((sha, datetime.fromisoformat(iso)))
    snaps.reverse()  # oldest first
    return snaps


def parse_snapshot(sha: str) -> dict[tuple[str, int], IssueRef]:
    """Parse RADAR.md at a given commit into {(repo, number): IssueRef}.

    Returns {} for snapshots whose ## headings look like repo names (owner/repo),
    which is the pre-Phase-4 RADAR.md format we don't try to reconcile.
    """
    try:
        text = run(["git", "show", f"{sha}:{RADAR_FILENAME}"])
    except subprocess.CalledProcessError:
        return {}
    headings = [
        m.group(1).strip()
        for line in text.splitlines()
        if (m := CATEGORY_HEADING.match(line)) and m.group(1).strip() not in NON_CATEGORY_SECTIONS
    ]
    if headings and all("/" in h for h in headings):
        return {}  # pre-Phase-4 layout — skip
    current_category: str | None = None
    result: dict[tuple[str, int], IssueRef] = {}
    for line in text.splitlines():
        h = CATEGORY_HEADING.match(line)
        if h:
            title = h.group(1).strip()
            current_category = None if title in NON_CATEGORY_SECTIONS else title
            continue
        if current_category is None:
            continue
        m = ISSUE_LINE.match(line)
        if not m:
            continue
        ref = IssueRef(
            category=current_category,
            repo=m.group("repo"),
            number=int(m.group("num")),
            kind=m.group("kind"),
            title=m.group("title").strip(),
        )
        result[ref.key] = ref
    return result


def category_counts(refs: dict[tuple[str, int], IssueRef]) -> dict[str, int]:
    counts: dict[str, int] = defaultdict(int)
    for r in refs.values():
        counts[r.category] += 1
    return dict(counts)


def render(
    snaps: list[tuple[str, datetime]],
    first: dict[tuple[str, int], IssueRef],
    last: dict[tuple[str, int], IssueRef],
) -> str:
    first_keys = set(first.keys())
    last_keys = set(last.keys())
    appeared = last_keys - first_keys
    vanished = first_keys - last_keys

    first_counts = category_counts(first)
    last_counts = category_counts(last)
    all_cats = sorted(set(first_counts) | set(last_counts))

    lines: list[str] = []
    lines.append(f"# Weekly Trends — {datetime.now(timezone.utc).date().isoformat()}")
    lines.append("")
    first_at = snaps[0][1].date().isoformat()
    last_at = snaps[-1][1].date().isoformat()
    lines.append(f"Window: {first_at} → {last_at} ({len(snaps)} snapshot{'s' if len(snaps) != 1 else ''})")
    lines.append("")
    lines.append(
        f"**Totals:** {len(first)} → {len(last)}"
        f"  ({len(appeared)} appeared, {len(vanished)} vanished)"
    )
    lines.append("")

    # Movement table
    lines.append("## Movement by category")
    lines.append("")
    lines.append("| Category | Start | End | Δ | Appeared | Vanished |")
    lines.append("|---|---:|---:|---:|---:|---:|")
    for cat in all_cats:
        start = first_counts.get(cat, 0)
        end = last_counts.get(cat, 0)
        cat_appeared = sum(1 for k in appeared if last[k].category == cat)
        cat_vanished = sum(1 for k in vanished if first[k].category == cat)
        delta = end - start
        delta_str = f"{delta:+d}" if delta else "0"
        lines.append(f"| {cat} | {start} | {end} | {delta_str} | {cat_appeared} | {cat_vanished} |")
    lines.append("")

    # Appeared, grouped by category (in order)
    if appeared:
        lines.append("## Appeared this week")
        lines.append("")
        by_cat: dict[str, list[IssueRef]] = defaultdict(list)
        for k in appeared:
            by_cat[last[k].category].append(last[k])
        for cat in all_cats:
            if cat not in by_cat:
                continue
            lines.append(f"### {cat}")
            lines.append("")
            for ref in sorted(by_cat[cat], key=lambda r: (r.repo, r.number)):
                url = f"https://github.com/{ref.repo}/issues/{ref.number}"
                lines.append(f"- [{ref.kind}] [{ref.repo}#{ref.number}]({url}) {ref.title}")
            lines.append("")

    # Vanished, grouped by category
    if vanished:
        lines.append("## Vanished this week")
        lines.append("")
        lines.append("_Likely closed, PR merged, or dropped from top 100 by activity — worth spot-checking._")
        lines.append("")
        by_cat = defaultdict(list)
        for k in vanished:
            by_cat[first[k].category].append(first[k])
        for cat in all_cats:
            if cat not in by_cat:
                continue
            lines.append(f"### {cat}")
            lines.append("")
            for ref in sorted(by_cat[cat], key=lambda r: (r.repo, r.number)):
                url = f"https://github.com/{ref.repo}/issues/{ref.number}"
                lines.append(f"- [{ref.kind}] [{ref.repo}#{ref.number}]({url}) {ref.title}")
            lines.append("")

    return "\n".join(lines)


def main() -> int:
    snaps = list_snapshots(WINDOW_DAYS)
    if not snaps:
        print("No RADAR.md snapshots in window — nothing to summarize.", file=sys.stderr)
        return 0

    # Skip snapshots we can't parse (e.g. pre-Phase-4 layout).
    parsed = [(sha, at, parse_snapshot(sha)) for sha, at in snaps]
    parsed = [p for p in parsed if p[2]]
    if len(parsed) < 2:
        print(
            f"Only {len(parsed)} parseable snapshot(s) in window — no diff possible yet.",
            file=sys.stderr,
        )
        return 0

    first_sha, first_at, first = parsed[0]
    last_sha, last_at, last = parsed[-1]
    parseable_snaps = [(sha, at) for sha, at, _ in parsed]

    WEEKLY_PATH.write_text(render(parseable_snaps, first, last))
    print(
        f"wrote {WEEKLY_PATH} "
        f"(window={len(parseable_snaps)} snapshots, "
        f"{len(first)} → {len(last)} issues)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
